In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0, 4.0, 1.0], [5.0, 6.0, 7.0]])
print(b)

[[9. 4. 1.]
 [5. 6. 7.]]


In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
b.dtype

dtype('float64')

In [13]:
b.itemsize

8

In [14]:
b.size

6

In [16]:
a = np.array([[4, 1, 5, 8, 2], [5, 2, 3, 8, 5]])
print(a)

[[4 1 5 8 2]
 [5 2 3 8 5]]


In [20]:
a[1, 4]

5

In [21]:
a[0, :]

array([4, 1, 5, 8, 2])

In [23]:
a[: , 2]

array([5, 3])

In [24]:
a[0, 1:4:2]

array([1, 8])

In [25]:
a[1, 4] = 20 

In [26]:
print(a)

[[ 4  1  5  8  2]
 [ 5  2  3  8 20]]


In [27]:
a[: , 1] = [3, 6]

In [28]:
print(a)

[[ 4  3  5  8  2]
 [ 5  6  3  8 20]]


In [29]:
b = np.array([[2, 6], [4, 9], [5, 8], [7, 7]])
print(b)

[[2 6]
 [4 9]
 [5 8]
 [7 7]]


In [30]:
b[1, 1]

9

In [43]:
c = np.array([[ [15, 29, 23, 12] , [19, 22, 26, 48] ], 
              [ [95, 55, 72, 88],  [11, 54, 36, 99 ] ]])
print(c)

[[[15 29 23 12]
  [19 22 26 48]]

 [[95 55 72 88]
  [11 54 36 99]]]


In [32]:
c[:, 1, 2]

array([26, 36])

In [33]:
c[:, 1, :]

array([[19, 22, 26, 48],
       [11, 54, 36, 99]])

In [34]:
#----------------------------

In [37]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [41]:
np.ones((4, 2, 5), dtype='int32')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [42]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [44]:
np.full_like(c, 4)

array([[[4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [45]:
np.random.rand(4, 2)

array([[0.31063417, 0.96646642],
       [0.70936848, 0.77341063],
       [0.22730765, 0.57087682],
       [0.18627682, 0.36037119]])

In [48]:
np.random.random_sample(c.shape)

array([[[0.3340598 , 0.64384466, 0.68931658, 0.57209637],
        [0.68391833, 0.177442  , 0.08250973, 0.20672285]],

       [[0.2758683 , 0.47546736, 0.4677375 , 0.48055095],
        [0.19321525, 0.02662117, 0.92750873, 0.31646793]]])

In [54]:
np.random.randint(55, size=(3, 3))

array([[43, 27, 41],
       [23, 31, 41],
       [12, 34, 24]])

In [56]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)

In [59]:
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [61]:
r2 = np.repeat(arr, 3, axis=1)
print(r2)

[[1 1 1 2 2 2 3 3 3]]


In [75]:
array = np.identity(5, dtype='int32')
array = np.full_like(array, 1)
print(array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [86]:
array[1:4, 1:4] = [0, 0, 0]
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [88]:
array[2, 2] = 9
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [89]:
#---------------------

In [90]:
a = np.array([1, 2, 3, 5])
print(a)

[1 2 3 5]


In [91]:
a + 2

array([3, 4, 5, 7])

In [92]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427])

In [93]:
#---------------------------

In [96]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [97]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [98]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [99]:
#--------------------

In [101]:
stats = np.array([ [1, 2, 3] , [4, 5, 6] ])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.min(stats)

1

In [103]:
np.max(stats)

6

In [104]:
np.min(stats, axis=1) # min of rows

array([1, 4])

In [105]:
np.min(stats, axis=0) # min of columns

array([1, 2, 3])

In [106]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [107]:
#------------------

In [109]:
before = np.array([ [1, 2, 3, 4], [5, 6, 7, 8] ])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [110]:
#---------------

In [111]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
#-------------------------------- Gen from file

In [113]:
#filedata = np.genfromtxt('data.txt', delimiter=',')
#filedata = filedata.astype('int32')

In [114]:
#---------------------------

In [116]:
#np.any(filedata > 50, axis=0)